### ISSUE TITLE
table not recognized by mweb

### ISSUE THREAD

**Issue by huahuayu** [crispgm/alfred-markdown-table#1]
below format is not recognized by mweb(a markdown editor in  mac)
```
table 3 2

Output:
|  |  |  |
|--|--|--|
|  |  |  |
|  |  |  |
```

instead, it should be , one more `-` please
```
|  |  |  |
|---|---|---|
|  |  |  |
|  |  |  |
```

**Comment by crispgm** [comment]
@huahuayu thanks, just fixed. please try with the latest version.

**Comment by huahuayu** [comment]
Ok
